# Generated by Django 4.2.4 on 2023-08-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='Not Set', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='Not Set', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Not Set', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='Not Set', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, default='Not Set', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pstu_id',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registration',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default='Not Set', max_length=100, null=True),
        ),
    ]
